[default]
DEBUG = false
EXTENSIONS = [
    "stock_management.ext.flask_sqlalchemy:init_app",
    "stock_management.ext.migrate:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "stock_management.ext.flask_sqlalchemy:init_app",
    "stock_management.ext.migrate:init_app",
]

[production]
