[default]
DEBUG = false
EXTENSIONS = [
    "",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "",
]

[production]
